### ISSUE TITLE
Please specify how to add the library to leanpkg.toml

### ISSUE THREAD

**Issue by JasonGross** [mhuisi/lean4-cli#3]
The README says:
https://github.com/mhuisi/lean4-cli/blob/58c23fca676bb7121be4eda6eae936fb98aa2507/README.md#L3

As a newcomer to Lean, I'm not sure how to add this package to my leanpkg.toml, and it'd be helpful if the documentation included the line to add (or an example line) or the command to run, if such a thing is feasible.

**Comment by mhuisi** [comment]
I'll resolve this issue when I'm done with exams, but for now you can find an example of how to include a dependency here: https://github.com/mhuisi/lean4-cli/blob/main/leanpkg.toml

**Comment by JasonGross** [comment]
Thanks!
