### ISSUE TITLE
subcommands should permit dashes

### ISSUE THREAD

**Issue by JasonGross** [mhuisi/lean4-cli#5]
```lean4
def cmd := `[Cli|
  foo-bar VIA doNothing; ["0.0.1"]
  "installCmd provides an example for a subcommand without flags or arguments."
]
```
gives
```
10:2:
unknown identifier 'foo'
10:6:
unknown identifier 'bar'
10:2:
failed to synthesize instance
  Sub String
```

But I'd like to be able to call subcommands on the command-line with dashes in the middle of them

**Comment by mhuisi** [comment]
One alternative for now until I get to this is to use `Cmd.mk` directly: https://github.com/mhuisi/lean4-cli/blob/58c23fca676bb7121be4eda6eae936fb98aa2507/Cli/Basic.lean#L718

**Comment by mhuisi** [comment]
Oh, I think you can use the DSL actually. Just put the name in quotes and it should work?

**Comment by JasonGross** [comment]
Ah, indeed that works, thanks!  It would be nice to get a better error message, but I'm happy to put things in quotes.
